### ISSUE TITLE
use resp.NextPage for pagination

### ISSUE THREAD

**Issue by willnorris** [barthr/issuestable#1]
rather that grabbing the LastPage value from a response and iterating until you hit that, it's better to look at the NextPage value from each individual response.  You also don't actually handle the error returned by `Issues.ListByRepo`; it just gets silently ignored.

Following the pattern documented at https://github.com/google/go-github#pagination, your code would become something like:

```go
var issues []*github.Issue
opt := &github.IssueListByRepoOptions{
	ListOptions: &github.ListOptions{PerPage: 100},
}
for {
	newIssues, resp, err := client.Issues.ListByRepo(path[1], path[2], opt)
	if err != nil {
		log.Fatalf("error fetching issues for %v/%v: %v", path[1], path[2], err)
	}

	issues = append(issues, newIssues...)
	if resp.NextPage == 0 {
		break
	}
	opt.ListOptions.Page = resp.NextPage
}
```

It's roughly the same amount of code, but adds in error handling and doesn't make any assumptions about how pages increment, making it a tad safer.

**Comment by barthr** [comment]
Thanks for pointing me to pagination part! I'll update the code and the blogpost. This looks way more elegant. 

I've changed the for loop a bit because now it will always fetch all the issues. Which isn't what we want when we specify the amount flag

```go
opt := &github.IssueListByRepoOptions{
	ListOptions: github.ListOptions{PerPage: 100},
}
var issues []*github.Issue

for len(issues) <= *amount || *amount < 0 {
	newIssues, resp, err := client.Issues.ListByRepo(path[1], path[2], opt)
	if err != nil {
		log.Fatalf("error fetching issues for %v/%v: %v", path[1], path[2], err)
	}

	issues = append(issues, newIssues...)
	if resp.NextPage == 0 {
		break
	}
	opt.ListOptions.Page = resp.NextPage
}
```
Good suggestion!

**Comment by willnorris** [comment]
> I've changed the for loop a bit because now it will always fetch all the issues. Which isn't what we want when we specify the amount flag

oh, good catch.  I had overlooked that flag.
